import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const time = new Date().toLocaleTimeString("en-US", {
		timeZone: "America/New_York",
	});

	return (
		<html lang="en">
			<body className="p-8 space-y-8 bg-zinc-100">
				<div>
					<h1>Root Layout</h1>
					<p>Time: {time}</p>
					<p>Random: {(Math.random() * 10).toFixed(1)}</p>
				</div>
				<div className="container">{children}</div>
			</body>
		</html>
	);
}
